server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=user_service_db
    hikari:
      username: postgres
      password: 123
      jdbc-url: jdbc:postgresql://localhost:5432/postgres?currentSchema=user_service_db
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  liquibase:
    enabled: true
    user: postgres
    password: 123
    default-schema: user_service_db
    liquibase-schema: user_service_db
    change-log: classpath:db/changelog/db.changelog-master.yaml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange: user-deletion-exchange
    routing-key: user-deletion
cache:
  time-to-live: 5
  max-entries: 10